version: '3.4'

services:
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: User.API/Dockerfile
    ports:
      - 46664:80
      - 46665:443
    environment:
      Consul__ID: User.API.46664
      Consul__Name: User.API
      Consul__IP: host.docker.internal
      Consul__Port: 46664

  user.api2:
    image: ${DOCKER_REGISTRY-}userapi
    build:
     context: .
     dockerfile: User.API/Dockerfile
    ports:
      - 46668:80
      - 46669:443
    environment:
      Consul__ID: User.API.46668
      Consul__Name: User.API
      Consul__IP: host.docker.internal
      Consul__Port: 46668
